version: '2'

services:
  php-fpm:
    build: ./docker/images/php-fpm
    container_name: payment.php
    expose:
      - 9000
    volumes:
      - ./docker/images/php-fpm/php-fpm.conf:/usr/local/etc/php-fpm.conf
      - ./docker/images/php-fpm/php.ini:/usr/local/etc/php/php.ini
      - ./app:/var/www/payment
  
  nginx:
    build: ./docker/images/nginx
    container_name: payment.nginx
    links:
      - php-fpm
    ports:
      - 8082:80
    volumes_from:
      - php-fpm
    volumes:
      - ./logs/nginx:/var/log/nginx/payment:rw