version: '2'


services:
  db:
      build:
        context: ./docker/images/percona
      container_name: payment.db
      environment:
        - MYSQL_DATABASE=${MYSQL_DATABASE}
        - MYSQL_USER=${MYSQL_USER}
        - MYSQL_PASSWORD=${MYSQL_PASSWORD}
        - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      volumes:
        - ./data/db:/var/lib/mysql
      ports:
        - 3306:3306
      expose:
        - 3306
      networks:
        - backend

  php-fpm:
    user: www-data
    container_name: payment.php-fpm
    env_file:
      - payment.env
    build:
      context: ./docker/images/php-fpm
      args:
          TIMEZONE: UTC
          XDEBUG_IP_ADDRESS: ${XDEBUG_IP_ADDRESS}
          PHP_ERROR_LOG_FILE: ${PHP_ERROR_LOG_FILE}
    expose:
      - 9000
    volumes:
      - ./docker/images/php-fpm/php-fpm.conf:/usr/local/etc/php-fpm.conf
      - ./workspace:/var/www/payment:rw
      - ./logs/php:/var/log/php:rw
      - ./logs/payment:/var/log/payment:rw
    networks:
      - backend
    links:
    - db:host.payment.db

  nginx:
    build: ./docker/images/nginx
    container_name: payment.nginx
    links:
      - php-fpm
    ports:
      - 8082:80
    volumes_from:
      - php-fpm
    volumes:
      - ./logs/nginx:/var/log/nginx/payment:rw
    networks:
      - backend

### Networks Setup ############################################

networks:
  backend:
    driver: "bridge"

volumes:
  mysql:
    driver: "local"